### ISSUE TITLE
Run VMs without redundancy options

### ISSUE THREAD

**Issue by parude-equinor** [Azure/karpenter-provider-azure#1002]
### Version

Hi guys,

Since 1.4.0 `topology.kubernetes.io/zone` can be used.
Can somebody help me to understand how can I use `topology.kubernetes.io/*` requirements to create VMs with NO availability options ("No infrastructure redundancy required" as per portal saying)?
In language of default AKS autoscaler through scalesets with no availability zone these labels are set as following:
```
metadata:
  labels:
    ...
    topology.kubernetes.io/region: northeurope
    topology.kubernetes.io/zone: '0'
    ...
```
But trying to set this requirements like that fails to provision the node further.

My setup:
k8s version: 1.31.2
karpenter (both crd chart and controller chart: 1.5.0

Thanks in advance!

### Expected Behavior

Karpenter can create VMs without redundancy options (no availability zone)

### Actual Behavior

Either it doesn't work or created VM uses the availability zone.

### Steps to Reproduce the Problem

Using karpenter >1.4.0 try to create VMs without redundancy options.

### Resource Specs and Logs

NodePool spec:
```
    spec:
      expireAfter: 24h
      nodeClassRef:
        group: karpenter.azure.com
        kind: AKSNodeClass
        name: default-karpenter-nodeclass
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: karpenter.azure.com/sku-name
          operator: In
          values:
            - Standard_D64s_v3
            - Standard_D48s_v3
            - Standard_D32s_v3
            - Standard_D16s_v3
            - Standard_D8s_v3
            - Standard_D4s_v3
        - key: gpupool
          operator: In
          values:
            - workloads
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - '0'
        - key: topology.kubernetes.io/region
          operator: In
          values:
            - 'northeurope'
```
AKSNodeClass spec:
```
spec:
  imageFamily: Ubuntu2204
  osDiskSizeGB: 100
```
Error I saw:
`Cannot disrupt NodeClaim: not all pods would schedule, karpenter/inflate-f77fb7b66-zld2r => incompatible with nodepool "workload-karpenter-nodepool", daemonset overhead={"cpu":"915m","memory":"2038922537","pods":"16"}, no instance type satisfied resources {"cpu":"1915m","memory":"10628857129","pods":"17"} and requirements gpupool In [workloads], karpenter.azure.com/sku-name In [Standard_D16s_v3 Standard_D32s_v3 Standard_D48s_v3 Standard_D4s_v3 Standard_D64s_v3 and 1 others], karpenter.sh/capacity-type In [on-demand], karpenter.sh/nodepool In [workload-karpenter-nodepool], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], node-restriction.aurora.equinor.com/purpose In [workloads], topology.kubernetes.io/region In [northeurope], topology.kubernetes.io/zone In [0] (no instance type met the scheduling requirements or had a required offering); incompatible with nodepool "spotworkload-karpenter-nodepool", daemonset overhead={"cpu":"915m","memory":"2038922537","pods":"16"}, no instance type satisfied resources {"cpu":"1915m","memory":"10628857129","pods":"17"} and requirements gpupool In [workloads], karpenter.azure.com/sku-name In [Standard_D16s_v3 Standard_D32s_v3 Standard_D48s_v3 Standard_D4s_v3 Standard_D64s_v3 and 1 others], karpenter.sh/capacity-type In [spot], karpenter.sh/nodepool In [spotworkload-karpenter-nodepool], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], node-restriction.aurora.equinor.com/purpose In [workloads], topology.kubernetes.io/region In [northeurope], topology.kubernetes.io/zone In [0] (no instance type met the scheduling requirements or had a required offering) karpenter/inflate-f77fb7b66-6mwr4 => incompatible with nodepool "workload-karpenter-nodepool", daemonset overhead={"cpu":"915m","memory":"2038922537","pods":"16"}, no instance type satisfied resources {"cpu":"1915m","memory":"10628857129","pods":"17"} and requirements gpupool In [workloads], karpenter.azure.com/sku-name In [Standard_D16s_v3 Standard_D32s_v3 Standard_D48s_v3 Standard_D4s_v3 Standard_D64s_v3 and 1 others], karpenter.sh/capacity-type In [on-demand], karpenter.sh/nodepool In [workload-karpenter-nodepool], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], node-restriction.aurora.equinor.com/purpose In [workloads], topology.kubernetes.io/region In [northeurope], topology.kubernetes.io/zone In [0] (no instance type met the scheduling requirements or had a required offering); incompatible with nodepool "spotworkload-karpenter-nodepool", daemonset overhead={"cpu":"915m","memory":"2038922537","pods":"16"}, no instance type satisfied resources {"cpu":"1915m","memory":"10628857129","pods":"17"} and requirements gpupool In [workloads], karpenter.azure.com/sku-name In [Standard_D16s_v3 Standard_D32s_v3 Standard_D48s_v3 Standard_D4s_v3 Standard_D64s_v3 and 1 others], karpenter.sh/capacity-type In [spot], karpenter.sh/nodepool In [spotworkload-karpenter-nodepool], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], node-restriction.aurora.equinor.com/purpose In [workloads], topology.kubernetes.io/region In [northeurope], topology.kubernetes.io/zone In [0] (no instance type met the scheduling requirements or had a required offering) karpenter/inflate-f77fb7b66-v9cmm => incompatible with nodepool "workload-karpenter-nodepool", daemonset overhead={"cpu":"915m","memory":"2038922537","pods":"16"}, no instance type satisfied resources {"cpu":"1915m","memory":"10628857129","pods":"17"} and requirements gpupool In [workloads], karpenter.azure.com/sku-name In [Standard_D16s_v3 Standard_D32s_v3 Standard_D48s_v3 Standard_D4s_v3 Standard_D64s_v3 and 1 others], karpenter.sh/capacity-type In [on-demand], karpenter.sh/nodepool In [workload-karpenter-nodepool], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], node-restriction.aurora.equinor.com/purpose In [workloads], topology.kubernetes.io/region In [northeurope], topology.kubernetes.io/zone In [0] (no instance type met the scheduling requirements or had a required offering); incompatible with nodepool "spotworkload-karpenter-nodepool", daemonset overhead={"cpu":"915m","memory":"2038922537","pods":"16"}, no instance type satisfied resources {"cpu":"1915m","memory":"10628857129","pods":"17"} and requirements gpupool In [workloads], karpenter.azure.com/sku-name In [Standard_D16s_v3 Standard_D32s_v3 Standard_D48s_v3 Standard_D4s_v3 Standard_D64s_v3 and 1 others], karpenter.sh/capacity-type In [spot], karpenter.sh/nodepool In [spotworkload-karpenter-nodepool], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], node-restriction.aurora.equinor.com/purpose In [workloads], topology.kubernetes.io/region In [northeurope], topology.kubernetes.io/zone In [0] (no instance type met the scheduling requirements or had a required offering) karpenter/inflate-f77fb7b66-rcpcg => incompatible with nodepool "workload-karpenter-nodepool", daemonset overhead={"cpu":"915m","memory":"2038922537","pods":"16"}, no instance type satisfied resources {"cpu":"1915m","memory":"10628857129","pods":"17"} and requirements gpupool In [workloads], karpenter.azure.com/sku-name In [Standard_D16s_v3 Standard_D32s_v3 Standard_D48s_v3 Standard_D4s_v3 Standard_D64s_v3 and 1 others], karpenter.sh/capacity-type In [on-demand], karpenter.sh/nodepool In [workload-karpenter-nodepool], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], node-restriction.aurora.equinor.com/purpose In [workloads], topology.kubernetes.io/region In [northeurope], topology.kubernetes.io/zone In [0] (no instance type met the scheduling requirements or had a required offering); incompatible with nodepool "spotworkload-karpenter-nodepool", daemonset overhead={"cpu":"915m","memory":"2038922537","pods":"16"}, no instance type satisfied resources {"cpu":"1915m","memory":"10628857129","pods":"17"} and requirements gpupool In [workloads], karpenter.azure.com/sku-name In [Standard_D16s_v3 Standard_D32s_v3 Standard_D48s_v3 Standard_D4s_v3 Standard_D64s_v3 and 1 others], karpenter.sh/capacity-type In [spot], karpenter.sh/nodepool In [spotworkload-karpenter-nodepool], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], node-restriction.aurora.equinor.com/purpose In [workloads], topology.kubernetes.io/region In [northeurope], topology.kubernetes.io/zone In [0] (no instance type met the scheduling requirements or had a required offering) karpenter/inflate-f77fb7b66-2gh7z => incompatible with nodepool "workload-karpenter-nodepool", daemonset overhead={"cpu":"915m","memory":"2038922537","pods":"16"}, no instance type satisfied resources {"cpu":"1915m","memory":"10628857129","pods":"17"} and requirements gpupool In [workloads], karpenter.azure.com/sku-name In [Standard_D16s_v3 Standard_D32s_v3 Standard_D48s_v3 Standard_D4s_v3 Standard_D64s_v3 and 1 others], karpenter.sh/capacity-type In [on-demand], karpenter.sh/nodepool In [workload-karpenter-nodepool], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], node-restriction.aurora.equinor.com/purpose In [workloads], topology.kubernetes.io/region In [northeurope], topology.kubernetes.io/zone In [0] (no instance type met the scheduling requirements or had a required offering); incompatible with nodepool "spotworkload-karpenter-nodepool", daemonset overhead={"cpu":"915m","memory":"2038922537","pods":"16"}, no instance type satisfied resources {"cpu":"1915m","memory":"10628857129","pods":"17"} and requirements gpupool In [workloads], karpenter.azure.com/sku-name In [Standard_D16s_v3 Standard_D32s_v3 Standard_D48s_v3 Standard_D4s_v3 Standard_D64s_v3 and 1 others], karpenter.sh/capacity-type In [spot], karpenter.sh/nodepool In [spotworkload-karpenter-nodepool], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], node-restriction.aurora.equinor.com/purpose In [workloads], topology.kubernetes.io/region In [northeurope], topology.kubernetes.io/zone In [0] (no instance type met the scheduling requirements or had a required offering) and 0 other(s)`

Disregard the similarity of the errors, I had almost identical nodepool for spot VMs.

The only correct option that worked for me now didn't solve my task (omitting these reqs also works):
```
    - key: topology.kubernetes.io/zone
      operator: In
      values:
        - northeurope-1
    - key: topology.kubernetes.io/region
      operator: In
      values:
        - northeurope
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
