### ISSUE TITLE
NodePool setup for specific GPU type

### ISSUE THREAD

**Issue by hoopty** [Azure/karpenter-provider-azure#1005]
I want to setup a NodePool for use when targeting a specific GPU type.  

For example, in workloads that will use the H100 GPU we have:
```
     spec:
       affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: nvidia.com/gpu.product
                 operator: In
                 values:
                 - NVIDIA-H100-NVL
```
and the NodePool I was trying is: 
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu-h100
spec:
  weight: 10
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
  template:
    spec:
      nodeClassRef:
        name: default
        kind: AKSNodeClass
        group: karpenter.azure.com
      taints:
        - key: sku
          value: gpu
          effect: NoSchedule
        # - key: nvidia.com/gpu
        #   value: "true"
        #   effect: NoSchedule
      requirements:
        # match what vllm is using for nodeAffinity
        - key: nvidia.com/gpu.product
          operator: Exists
        - key: karpenter.azure.com/sku-name
          operator: In
          values:
            - Standard_NC40ads_H100_v5
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
            - reserved
            - spot
      startupTaints:
        - effect: NoExecute
          key: node.cilium.io/agent-not-ready
          value: "true"
```

But NAP did not trigger the creation of NodeClaims for the `gpu-h100` NodePool.
