### ISSUE TITLE
`karpenter.azure.com/zone` requirement causes continuous drift

### ISSUE THREAD

**Issue by tallaxes** [Azure/karpenter-provider-azure#205]
### Version

__Karpenter Version:__ https://github.com/Azure/karpenter-provider-azure/commit/99d1bb0730b3462e40267ec28024368c90801b26 (current main)

__Kubernetes Version:__ v1.27.9

### Expected Behavior

One should be able to specify requirements with `karpenter.azure.com/zone` constraint, for example to only provision nodes in a specific zone, without adverse effects.

### Actual Behavior

Specifying any kind of `karpenter.azure.com/zone` constraint in a NodePool current triggers continuous drift.

Here is what I am thinking is going on. Right now, we cannot (and do not) record this requirement/constraint as a label on NodeClaim. This is because Karpenter will try applying all of these as labels to Node object - and `topology.kubernetes.io/zone`
is a protected label in AKS. (It will be applied to a new Node correctly, but by a different component). So for now, as a workaround, we use an alternative label `karpenter.azure.com/zone`. I suspect that it is this discrepancy that causes Karpenter to detect Requirements Drift: Based of NodePool, the NodeClaim is expected to have the zone label, and it does not => out of spec, to be replaced. I also suspect that, while we do have E2E tests in this area, they likely only test that the node gets provisioned, and don't notice the subsequent drift.

### Steps to Reproduce the Problem

Use NodePool with any kind of `karpenter.azure.com/zone` requirement.

### Resource Specs and Logs

Continuous drift observed.

### Workaround

Specify zone-based constraints (including `topologySpreadConstraint`, if needed) via workload, rather than NodePool.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by nfsouzaj** [comment]
Hello @tallaxes @Bryce-Soghigian 

I've been throughly testing karpenter as I plan to leverage it on my workloads and I am also having problems with the zone configuration in the nodepool. I have a nodepool configured with the following requirement:
`...
        - key: karpenter.azure.com/zone
          operator: In
          values: ["eastus-1", "eastus-2", "eastus-3"]
`
Whenever I apply it, i get the following message:
`The NodePool "krptpool" is invalid: spec.template.spec.requirements[6].key: Invalid value: "string": label domain "karpenter.azure.com" is restricted`. 

Thus, the workaround mentioned doesn't seem to work (unless I am doing something really silly).

Can you guys please take a look at it? 

Also, I would like to point out that the documentation here https://learn.microsoft.com/en-us/azure/aks/node-autoprovision?tabs=azure-cli#sku-selectors-with-well-known-labels provides another key (also reserved) that doesn't work _topology.kubernetes.io/zone_ so it would be a good idea to update it imo.

**Comment by arvi3411301** [comment]
We’re facing the issue. Any workaround?

**Comment by Defman** [comment]
Looks like `topology.kubernetes.io/zone` is not part of the crd for nodepool.
https://github.com/Azure/karpenter-provider-azure/blob/da8f3538cb38c223413dd6e15ea5efc8486322fc/charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml#L200C1-L200C35

However `failure-domain.beta.kubernetes.io/zone` is supported in the crd.

**Comment by tallaxes** [comment]
Specifying topology spread constraint on `topology.kubernetes.io/zone` in the workload should work, please retest (and let us know if there are any problems).

Specifying `topology.kubernetes.io/zone` requirement in NodePool is not currently supported.

**Comment by Defman** [comment]
It is possible to use topology spread constraint on `topology.kubernetes.io/zone` however karpenter does not care and will schedule a node on an incompatible zone.

**Comment by tallaxes** [comment]
> It is possible to use topology spread constraint on topology.kubernetes.io/zone however karpenter does not care and will schedule a node on an incompatible zone.

Could you provide more details on your configuration?

**Comment by Defman** [comment]
Hhere is our `AKSNodeClass` and `NodePool`.
```yaml
---
apiVersion: karpenter.azure.com/v1alpha2
kind: AKSNodeClass
metadata:
  name: default-azurelinux
  annotations:
    kubernetes.io/description: "General purpose AKSNodeClass for running ZureLinux nodes"
spec:
  imageFamily: AzureLinux
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default-azurelinux
spec:
  weight: 10
  limits:
    cpu: "512"
    memory: 1Ti
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 * 24h = 720h
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: karpenter.azure.com/sku-family
          operator: In
          values:
            - D
      startupTaints:
        - effect: NoExecute
          key: node.cilium.io/agent-not-ready
          value: "true"
      nodeClassRef:
        name: default-azurelinux
```

**Comment by Defman** [comment]
Hi @tallaxes is the above provided information enough to identify the issue?

Kind regards, Jacob

**Comment by michiwerner** [comment]
I really needed to get this to work because I have a cluster that is using zonal Premium SSD v2 disks, and found the following to work - posting it here in case anyone else is desperate and coming across this thread:

In the NodePool requirements:
```
- key: topology.disk.csi.azure.com/zone
  operator: In
  values: ["germanywestcentral-1", "germanywestcentral-2", "germanywestcentral-3"]
```

And then in a deployment that e.g. needs a disk in zone 1:
```
nodeSelector:
    topology.disk.csi.azure.com/zone: germanywestcentral-1
```

Hope this helps.

**Comment by tallaxes** [comment]
@Defman, have not had a chance to try reproduce this yet

Everybody: @comtalyst may have found a way to allow specifying `topology.kubernetes.io/zone` requirement in NodePool (and make it work), expect to see some progress in this space soon

**Comment by Defman** [comment]
@tallaxes, I'm conducting further tests. I've observed that all nodes provisioned by Karpenter are currently launching only within the `westeurope-1` availability zone. I suspect this might be due to a misconfiguration on our end. To help investigate, I've provided the Karpenter environment variables. Could you take a look when you get a chance?

```
- env:
    - name: KUBERNETES_SERVICE_HOST
        value: REDACTED
    - name: KUBERNETES_PORT
        value: REDACTED
    - name: KUBERNETES_PORT_443_TCP
        value: REDACTED
    - name: KUBERNETES_PORT_443_TCP_ADDR
        value: REDACTED
    - name: KUBERNETES_MIN_VERSION
        value: 1.19.0-0
    - name: KARPENTER_SERVICE
        value: karpenter
    - name: WEBHOOK_PORT
        value: "8443"
    - name: WEBHOOK_METRICS_PORT
        value: "8001"
    - name: DISABLE_WEBHOOK
        value: "false"
    - name: LOG_LEVEL
        value: info
    - name: METRICS_PORT
        value: "8080"
    - name: HEALTH_PROBE_PORT
        value: "8081"
    - name: SYSTEM_NAMESPACE
        valueFrom:
        fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
    - name: MEMORY_LIMIT
        valueFrom:
        resourceFieldRef:
            containerName: controller
            divisor: "0"
            resource: limits.memory
    - name: FEATURE_GATES
        value: SpotToSpotConsolidation=false
    - name: BATCH_MAX_DURATION
        value: 10s
    - name: BATCH_IDLE_DURATION
        value: 1s
    - name: VM_MEMORY_OVERHEAD_PERCENT
        value: "0.075"
    - name: CLUSTER_NAME
        value: REDACTED
    - name: CLUSTER_ENDPOINT
        value: REDACTED
    - name: KUBELET_BOOTSTRAP_TOKEN
        value: REDACTED
    - name: SSH_PUBLIC_KEY
        value: |
        ssh-rsa REDACTED
    - name: NETWORK_PLUGIN
        value: azure
    - name: NETWORK_PLUGIN_MODE
        value: overlay
    - name: NETWORK_POLICY
        value: azure
    - name: VNET_SUBNET_ID
        value: REDACTED
    - name: VNET_GUID
        value: REDACTED
    - name: NODE_IDENTITIES
        value: REDACTED
    - name: ARM_SUBSCRIPTION_ID
        value: REDACTED
    - name: USE_SIG
        value: "false"
    - name: LOCATION
        value: westeurope
    - name: AZURE_NODE_RESOURCE_GROUP
        value: REDACTED
    - name: AZURE_CLIENT_ID
        value: REDACTED
    - name: AZURE_TENANT_ID
        value: REDACTED
    - name: AZURE_FEDERATED_TOKEN_FILE
        value: REDACTED
    - name: AZURE_AUTHORITY_HOST
        value: https://login.microsoftonline.com/
```
