### ISSUE TITLE
Karpenter sometimes cannot create nodes/NodeClaims for workloads with zone affinity constraints

### ISSUE THREAD

**Issue by comtalyst** [Azure/karpenter-provider-azure#339]
### Version

__Karpenter Version:__ v0.4.0

__Kubernetes Version:__ v1.28.5

### Expected Behavior

When deploying a workload with zone affinity constraints such as below and scale-up is required, the scaleup should occur, with both NodeClaims and nodes created to handle the workloads.
```
preferredDuringSchedulingIgnoredDuringExecution:
- podAffinityTerm:
    labelSelector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - inflate
    topologyKey: topology.kubernetes.io/zone
  weight: 100
```

### Actual Behavior

NodeClaims might not be created, and the error log below might occur:
```
The NodeClaim "..." is invalid: spec.requirements[3].key: Invalid value: "string": label domain "kubernetes.io" is restricted
```
The requirements index can be varied.

### Steps to Reproduce the Problem

Deploy a deployment with above affinity on a zoned region.

### Resource Specs and Logs

See above.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
