### ISSUE TITLE
kaito repro

### ISSUE THREAD

**Issue by Bryce-Soghigian** [Azure/karpenter-provider-azure#356]
Applying a nodepool like this it will not join the cluster. IF you use a different instance type that has quota it will. for some reason we filter out nc6s_v3.  Next steps for testing could be to use the sku-gen scripts on the upstream e2e sub that kaito uses to see if any subscription limits are being applied by karpenter. 

Here is a yaml taht works for other instance types but not for NC6_v3

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodeClaim
metadata:
  name: test-gpu-nodeclaim
  labels:
    karpenter.sh/nodepool: silly-goose
  annotations:
    karpenter.sh/do-not-disrupt: "true"
spec:
  nodeClassRef:
    name: default
  requirements:
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - standard_nc6s_v3
```
