### ISSUE TITLE
PVC with storageClass: default renders karpenter unable to schedule pods

### ISSUE THREAD

**Issue by tpaul1611** [Azure/karpenter-provider-azure#497]
### Version

__Karpenter Version:__ v0.5.4

__Kubernetes Version:__ v1.30.3

### Expected Behavior

A PersistendVolumeClaim with storageClass: default should work out of the box.

### Actual Behavior

As described in the logs, since the storageClass default does not have any availability zone restrictions, karpenter tags the pod with an empty list of required zones, which effectively makes all existing SKUs incompatible.

If the storageClass does not have any zone restrictions, karpenter should not add the topology.disk.csi.azure.com/zone tag at all.

### Steps to Reproduce the Problem

Try scheduling any pod with a PVC (storageClass: default, probably any of the AKS preconfigured storage classes) with self-hosted NAP.

### Resource Specs and Logs

    {"level":"DEBUG","time":"2024-09-24T07:07:33.059Z","logger":"controller.provisioner","message":"adding requirements derived from pod volumes, [{topology.disk.csi.azure.com/zone In []}]","commit":"846ef96","pod":"dependency-track/dependency-track-apiserver-6689598c68-5258j"}
    {"level":"DEBUG","time":"2024-09-24T07:07:33.061Z","logger":"controller.provisioner","message":"27 out of 503 instance types were excluded because they would breach limits","commit":"846ef96","nodepool":"weeu-shared-services-spot"}
    {"level":"INFO","time":"2024-09-24T07:07:33.063Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"846ef96","pods":"dependency-track/dependency-track-apiserver-6689598c68-5258j","duration":"10.69571ms"}
    {"level":"ERROR","time":"2024-09-24T07:07:33.063Z","logger":"controller.provisioner","message":"Could not schedule pod, incompatible with nodepool \"weeu-shared-services-spot\", daemonset overhead={\"cpu\":\"250m\",\"memory\":\"470Mi\",\"pods\":\"7\"}, no instance type satisfied resources {\"cpu\":\"2250m\",\"memory\":\"8662Mi\",\"pods\":\"8\"} and requirements karpenter.azure.com/sku-family In [D F], karpenter.sh/capacity-type In [spot], karpenter.sh/nodepool In [weeu-shared-services-spot], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], topology.kubernetes.io/zone In [] (no instance type met all requirements)","commit":"846ef96","pod":"dependency-track/dependency-track-apiserver-6689598c68-5258j"}

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tallaxes** [comment]
Reproduced. Likely has to do with the way we represent zones in offerings. Also need to add E2E test suit for storage.

**Comment by comtalyst** [comment]
I could not reproduce the issue anymore, at least from the below deployments. The node is created and pods scheduled fine. 
Thus, I think it is fixed—by one of the past changes(?).

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 6
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      containers:
      - image: mcr.microsoft.com/oss/kubernetes/pause:3.6
        name: inflate
        resources:
          requests:
            cpu: "1"
            memory: 256M
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: my-pvc
```
