### ISSUE TITLE
How is karpenter is supporting Azure

### ISSUE THREAD

**Issue by abhishek-baranwal** [Azure/karpenter-provider-azure#509]
### What karpenter features are relevant?

Hi team,

Just want to understand how karpenter works with azure AKS
I saw microsoft documentation which says below that there is limitation while working with AKS, we can not create virtual machine scaleset with karpenter while  Karpenter is not designed to directly create Virtual Machine Scale Sets (VMSS) in Azure; instead, it focuses on automatically provisioning individual nodes within a Kubernetes cluster based on pod requirements, essentially bypassing the need to manage VMSS explicitly, allowing for more granular scaling and cost optimization by launching only the necessary nodes. 

**The AKS cluster must use Virtual Machine Scale Sets for the nodes.**
reference: https://learn.microsoft.com/en-gb/azure/aks/create-node-pools#limitations

we also found some issue related to it while we were trying to create internal azure LB, it was showing error
`Error syncing load balancer: failed to ensure load balancer: can not extract scale set name from ipConfigurationID (/subscriptions/xxxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Network/networkInterfaces/aks-karpenter-nodepool-xxxx/ipConfigurations/aks-karpenter-nodepool-xxxx)`

let me know if there is something wrong with our service below

````yaml
apiVersion: v1
kind: Service
metadata:
  name: service-loadbalancer
  labels:
    app: service-loadbalancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: xxxxxx
spec:
  type: LoadBalancer
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: service
  ports:
    - protocol: TCP
      port: 80
  sessionAffinity: None
````

### How should the docs be improved?

Please update the doc which inform more details on this limitation and this issue in some troubleshooting doc

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
