### ISSUE TITLE
Error when applying nodepool manifest that contains karpenter.azure.com/zone key

### ISSUE THREAD

**Issue by nfsouzaj** [Azure/karpenter-provider-azure#512]
### Version

__Karpenter Version:__ 
karpenter-overlay-addon-0.1.0-127f4bc9300cca9fa11d1616aca290c47bccdcf0
karpenter-overlay-base-addon-0.1.0-40fdfd1faef52d126cf72f22cf1050a5c781a4e7

__Kubernetes Version:__ v1.29.7

### Expected Behavior

I expect a Nodepool manifest that allows me to set as requirement `karpenter.azure.com/zone` or any other key which determines avaibility zones.

### Actual Behavior

Once I apply the following manifest:

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: krptpool
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  template:
    spec:
      nodeClassRef:
        name: iceclass
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.azure.com/sku-family
          operator: In
          values: ["D"]
        - key: karpenter.azure.com/zone
          operator: In
          values: ["eastus-1", "eastus-2", "eastus-3"]
```

I get the following error: 

`The NodePool "krptpool" is invalid: spec.template.spec.requirements[6].key: Invalid value: "string": label domain "karpenter.azure.com" is restricted`

### Steps to Reproduce the Problem

Apply the manifest above in a cluster that has karpenter deployed via Azure add-on

### Resource Specs and Logs

It seems like the "default" behavior

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
