### ISSUE TITLE
BUG: Seeing Cases of Immediate Consolidation

### ISSUE THREAD

**Issue by charliedmcb** [Azure/karpenter-provider-azure#581]
### Version

__Karpenter Version:__ HEAD: [v0.7.0](https://github.com/Azure/karpenter-provider-azure/releases/tag/v0.7.0)+[636ca33](https://github.com/Azure/karpenter-provider-azure/commit/636ca333e52e153eb854d69d07d2b8eb3c7bbd05)

__Kubernetes Version:__ v1.29.9

### Expected Behavior

Karpenter to scale in the correct sized instances needed for my workload.

### Actual Behavior

Karpenter scaled in a few `Standard_D2as_v5` instances with resourcing:
![Image](https://github.com/user-attachments/assets/a809c3a8-dc47-4837-b6c4-77f405573fc0)
https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/general-purpose/dasv5-series?tabs=sizebasic

And then quickly detected underutilization replacing them with `Standard_D2ls_v5` instances with resourcing:
![Image](https://github.com/user-attachments/assets/f7d2a649-1ae4-474a-9986-04aada271da8)
https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/general-purpose/dlsv5-series?tabs=sizebasic

### Steps to Reproduce the Problem

1. Deploy self-hosted Karpenter to a cluster
2. Deploy the following NodePool + AKSNodeClass
``` 
# This example NodePool will provision general purpose instances
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general-purpose
  annotations:
    kubernetes.io/description: "General purpose NodePool"
spec:
  disruption:
    consolidateAfter: 1m
    budgets:
    - nodes: "5"
  limits:
    cpu: 30
  template:
    metadata:
      labels:
        # required for Karpenter to predict overhead from cilium DaemonSet
        kubernetes.azure.com/ebpf-dataplane: cilium
    spec:
      nodeClassRef:
        group: karpenter.azure.com
        kind: AKSNodeClass
        name: default
      startupTaints:
      # https://karpenter.sh/docs/concepts/nodepools/#cilium-startup-taint
      - key: node.cilium.io/agent-not-ready
        effect: NoExecute
        value: "true"
      expireAfter: Never
      requirements:
      - key: karpenter.azure.com/sku-cpu
        operator: Lt
        values: ["3"]
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64"]
      - key: kubernetes.io/os
        operator: In
        values: ["linux"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
      - key: karpenter.azure.com/sku-family
        operator: In
        values: [D]
---
apiVersion: karpenter.azure.com/v1alpha2
kind: AKSNodeClass
metadata:
  name: default
  annotations:
    kubernetes.io/description: "General purpose AKSNodeClass for running Ubuntu2204 nodes"
spec:
  imageFamily: Ubuntu2204
```
3. Deploy inflate deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 10
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      containers:
      - image: mcr.microsoft.com/oss/kubernetes/pause:3.6
        name: inflate
        resources:
          requests:
            cpu: "1.1"
            memory: 256M
```
4. Should scale in a collection of nodes.
5. Watch for consolidation:
```
{
  "level": "INFO",
  "time": "2024-11-19T23:48:57.433Z",
  "logger": "controller",
  "message": "disrupting nodeclaim(s) via replace, terminating 1 nodes (1 pods) aks-general-purpose-dgk4c/Standard_D2as_v5/on-demand and replacing with on-demand node from types Standard_D2ls_v5",
  "commit": "636ca33",
  "controller": "disruption",
  "namespace": "",
  "name": "",
  "reason": "underutilized"
}
```

### Resource Specs and Logs

See important resources in the repro section.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
