### ISSUE TITLE
SKU-image/disk incompatibility

### ISSUE THREAD

**Issue by CCOLLOT** [Azure/karpenter-provider-azure#616]
### Version

Starting this morning in Europe West, I started getting these errors:

The VM size 'Standard_D4als_v6' cannot boot with OS image or disk. Please check that disk controller types supported by the OS image or disk is one of the supported disk controller types for the VM size 'Standard_D4als_v6'. Please query sku api at https://aka.ms/azure-compute-skus to determine supported disk controller types for the VM size.

nodepool config:

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: app
spec:
  disruption:
    budgets:
    - nodes: 20%
    - duration: 8h
      nodes: "0"
      schedule: 0 8 * * mon-fri
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  template:
    metadata:
      labels:
        foo.bar/workload-type: app
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.azure.com/sku-family
        operator: In
        values:
        - E
        - D
      - key: karpenter.azure.com/sku-cpu
        operator: In
        values:
        - "4"
        - "8"
  weight: 100
```

### Expected Behavior

I expect NAP to check such compatibilities issues or at least to retry with a different node type / disk type /os image if it gets this kind of errors

### Actual Behavior

No node is provisioned

### Steps to Reproduce the Problem

Not 100% certain but I assume trying to launch a Standard_D4als_v6 node with the latest azure linux image

### Resource Specs and Logs

The VM size 'Standard_D4als_v6' cannot boot with OS image or disk. Please check that disk controller types supported by the OS image or disk is one of the supported disk controller types for the VM size 'Standard_D4als_v6'. Please query sku api at https://aka.ms/azure-compute-skus to determine supported disk controller types for the VM size.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tallaxes** [comment]
As a temporary workaround, add a constraint excluding v6:
```yaml
- key: karpenter.azure.com/sku-version
  operator: Lt
  values: ["6"]
```
