### ISSUE TITLE
how to allow karpenter to only use sku with ephemeral OS disk support ?

### ISSUE THREAD

**Issue by flbla** [Azure/karpenter-provider-azure#683]
### Version

__Karpenter Version:__ 0.7.2

__Kubernetes Version:__ v1.30.5

I would like Karpenter to only use SKU with ephemeral OS disk support, I tried : 

```
        - key: karpenter.azure.com/sku-storage-ephemeralos-maxsize
          operator: Gt
          values: ["0"]
```
but it didn't work.

### Expected Behavior

be able to force karpenter to only deploy node with ephemeral OS disk 

### Actual Behavior

it doesn't work

### Steps to Reproduce the Problem

```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general-purpose
  annotations:
    kubernetes.io/description: "General purpose NodePool for generic workloads"
spec:
  template:
    metadata:
      labels:
        purpose: general
        environment: production
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64", "arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand", "spot"]
        - key: karpenter.azure.com/sku-storage-ephemeralos-maxsize
          operator: Gt
          values: ["0"]
        - key: karpenter.azure.com/sku-encryptionathost-capable
          operator: In
          values: ["true"]
      nodeClassRef:
        group: karpenter.azure.com
        kind: AKSNodeClass
        name: default
      taints:
        - key: dedicated
          value: general
          effect: NoSchedule
```

### Resource Specs and Logs

karpenter-b8447f954-ll2q4 controller {"level":"ERROR","time":"2025-02-07T13:06:52.628Z","logger":"controller","caller":"provisioning/provisioner.go:359","message":"could not schedule pod","commit":"b3ec519","controller":"provisioner","namespace":"","name":"","reconcileID":"baa84319-01af-4775-a51b-bc9d909e734d","Pod":{"name":"inflate-847f7fbf56-hpz4t","namespace":"karpenter"},"error":"incompatible with nodepool \"general-purpose\", daemonset overhead={\"cpu\":\"850m\",\"memory\":\"1262Mi\",\"pods\":\"9\"}, no instance type satisfied resources {\"cpu\":\"1850m\",\"memory\":\"1262Mi\",\"pods\":\"10\"} and requirements environment In [production], karpenter.azure.com/sku-encryptionathost-capable In [true], karpenter.azure.com/sku-storage-ephemeralos-maxsize Exists >0, karpenter.sh/capacity-type In [on-demand spot], karpenter.sh/nodepool In [general-purpose], kubernetes.io/arch In [amd64 arm64], kubernetes.io/os In [linux], purpose In [general] (no instance type met all requirements)"}                                                                                                

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
