### ISSUE TITLE
Kubelet Bootstrap Token Parameter in Helm Chart

### ISSUE THREAD

**Issue by Gabryel8818** [Azure/karpenter-provider-azure#695]
Hey guys, how are you? :D 

I'am excited to use Karpenter Self Hosted in AKS, but, I look one problem in actually configuration

In AWS EKS the karpenter don't need Kubelet Bootstrap Token in helm chart values, but in this project yes

Exist any motivation for this? the karpenter controller can't get this token on your own before join a new machine in cluster?

**Comment by superff** [comment]
this token will expire in a few days, it is causing issue for us

**Comment by Bryce-Soghigian** [comment]
> this token will expire in a few days, it is causing issue for us

Just to be clear, this is for self-hosted karpenter you are having this problem right? We manage the token in managed karpenter, but there is room for improvement for self-hosted.

**Comment by nesmanriquecelonis** [comment]
> > this token will expire in a few days, it is causing issue for us
> 
> Just to be clear, this is for self-hosted karpenter you are having this problem right? We manage the token in managed karpenter, but there is room for improvement for self-hosted.

@Bryce-Soghigian any pointers on how to manage this token in self-hosted version? Do you regenerate the token with a sidecar? How often should this be done? Just before expiry or for every node/nodepool like it says in [this comment in the code](https://github.com/Azure/karpenter-provider-azure/blob/main/pkg/operator/options/options.go#L67)?

**Comment by simonswu23** [comment]
Was running into this issue as well for self-hosted, and found a temporary workaround. Here's what we did:
- created a secret to store the bootstrap token
- modified the karpenter-values file to point to the secret as a reference instead of the raw token
- created a cronjob in kube-system to generate and pull a new token into the secret file every ~12 hours or so

It's been working for the past 2 weeks or so with no issues

**Comment by mkilchhofer** [comment]
Why not allowing karpenter via `ClusterRole + ClusterRoleBinding` to read the bootstrap tokens available in `kube-system` namespace via Kube-API (everytime Karpenter initializes a new node)?

**Comment by JoeBouchard** [comment]
Currently, we are getting around this by deploying Karpenter to the `kube-system` namespace directly, then referencing one of the bootstrap tokens in the Helm chart. However, in AKS, when Kubernetes updates or the nodes are upgraded, it seems like the tokens get wiped away and regenerated. This happened to us just yesterday during our Sunday morning update window. Since the annotations for the bootstrap token are well known, it would make sense for Karpenter to read a bootstrap token on startup using the Kube API. We have had good success with Karpenter in our Dev environment, but we can't promote it to Prod until we get this issue resolved.

**Comment by johngmyers** [comment]
I looked into this and the process is insecure, fragile, and difficult to manage.

* The documented `hack/deploy/configure-values.sh` just grabs an arbitrary bootstrap token out of the `kube-system` namespace, without verifying the usability of the token. If the token the script finds just happens to not have the necessary usage enabled, things will fail.
* The tokens that exist in the `kube-system` namespace on an AKS cluster have no expiration. So if a token leaks, perhaps through a subsequently-terminated employee, the leaked token potentially remains able to compromise the cluster as long as the cluster exists. The Azure provider doesn't appear to be able to deal with renewing tokens in any case.
* The token is passed to karpenter through an environment variable in the pod template, leaking it to any user able to list Pods or Deployments in the `kube-system` namespace.
* The documented process is to manually run a provided script in order to extract this information, reformat it, and pass it through Helm values. This does not work with automated deployment systems such as Flux.

The Azure provider should simply create its own tokens, not rely on tokens created by an unrelated service/addon. It should read the token Secrets directly, not use an insecure and roundabout mechanism such as the environment. It should set an expiration on the tokens it generates and rotate them at a reasonable interval.

**Comment by JoeBouchard** [comment]
Deploying with Helm, this is my roundabout solution that seems to work. Essentially, it creates a sidecar container that copies the values of a bootstrap token into a new secret, then references that secret in the Helm file. It's not very clean. It would be much better with init containers, but those aren't configurable in the Helm chart. Feel free to bash this solution, I want to do it better. Ideally, it could also select a token based on the permissions the token has, and it wouldn't rely on a sidecar container kept alive by `sleep infinity`. All that being said, it seems to be working and be about as secure as it can be. I do have Karpenter deployed in `kube-system`, which makes it all a little easier, but changing the namespace of the token can be done in the `jq` command.

```
additionalClusterRoleRules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["patch", "update"]
  resourceNames:
    - "karpenter-bootstrap-token"
controller:
  sidecarContainer:
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
      - sh 
      - "-c" 
      - kubectl get secrets --field-selector type=bootstrap.kubernetes.io/token -n kube-system -o=jsonpath="{.items[0]}" | jq 'del(.metadata["namespace","creationTimestamp","resourceVersion","selfLink","uid","ownerReferences","annotations","labels"]) | .metadata.name = "karpenter-bootstrap-token"' | kubectl apply -n kube-system -f - && sleep infinity
  env:
    - name: TOKEN_ID
      valueFrom:
        secretKeyRef:
          name: karpenter-bootstrap-token
          key: token-id
    - name: TOKEN_SECRET
      valueFrom:
        secretKeyRef:
          name: karpenter-bootstrap-token
          key: token-secret
    - name: KUBELET_BOOTSTRAP_TOKEN
      value: $(TOKEN_ID).$(TOKEN_SECRET)
```

**Comment by johngmyers** [comment]
That's a bit Rube Goldbergian, but it's what's needed to work around the original bad design. It avoids leaking the token secret through the Pod and Deployment objects, but not leaking through `ps` on the node running Karpenter.

Also doesn't address the concerns around expiration and usage suitability.

**Comment by JoeBouchard** [comment]
Right. My idea is that if the token expires, Karpenter will crash. When it crashes, it'll restart that kubectl container and pull a new unexpired token. I'm sure with a bit more tweaking, we could adjust the command to filter out expired tokens. There's probably some way to get the sidecar to trigger a restart if it detects that a token has changed. But all that feels even more Rube Goldberg.

**Comment by johngmyers** [comment]
I doubt Karpenter would crash. More likely, the nodes it creates would simply fail to join the cluster.

**Comment by JoeBouchard** [comment]
Here's a couple tweaks to my solution from earlier. It's messier than I'd like, but it works. Essentially, the sidecar container acts like a Job. It creates/updates the secret `karpenter-bootstrap-token` by copying an existing bootstrap token into it. It runs every 15 seconds, so changes are propagated quickly. It would be better to do it as a Job, but there is no place to add a Job to the Helm chart. 

In addition, we use Stakater Reloader at my company, which automatically redeploys a Deployment if there is a change to a dependent ConfigMap or Secret and the Deployment has the right annotation. As part of my solution, I added that annotation in the Helm chart. The sidecar kubectl container could also restart the deployment, but for my purposes, I used our existing solution to do that. Now, when the bootstrap token is copied and changed, Karpenter will restart with a new fresh token. 

The last thing to add would be a check for if the token is expired, but we don't use temporary tokens in our use case, so that ideally won't affect us. 

```
additionalAnnotations:
  reloader.stakater.com/auto: "true"
additionalClusterRoleRules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["patch", "update"]
  resourceNames:
    - "karpenter-bootstrap-token"
controller:
  sidecarContainer:
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
      - sh 
      - "-c" 
      - |
        while true; do kubectl get secrets --field-selector type=bootstrap.kubernetes.io/token -n kube-system -o=jsonpath="{.items[0]}" | jq 'del(.metadata["namespace","creationTimestamp","resourceVersion","selfLink","uid","ownerReferences","annotations","labels"]) | .metadata.name = "karpenter-bootstrap-token"' | kubectl apply -n kube-system -f - && sleep 15s; done
  env:
    - name: TOKEN_ID
      valueFrom:
        secretKeyRef:
          name: karpenter-bootstrap-token
          key: token-id
    - name: TOKEN_SECRET
      valueFrom:
        secretKeyRef:
    - name: karpenter-bootstrap-token
      key: token-secret
      - name: KUBELET_BOOTSTRAP_TOKEN
        value: $(TOKEN_ID).$(TOKEN_SECRET)
```

**Comment by dunefro** [comment]
I am not sure but there is no secret in our entire AKS cluster which has this label key `bootstrap.kubernetes.io/token`. We are currently running AKS version 1.31 and I am not sure how the above responders are able to retrieve the secret. 

Moreover the entire process of self hosted installation is not fully clear and the documentation is missing lot of pieces. 

- No clear mention of serviceaccount annotations and how to use them
- karpenter helm chart current version (as of the time of this comment) is 1.5.5 and the document has it 0.7.0. 
- Deploy scripts dont' work anymore as the karpenter template values file doesn't exist anymore.
- helm chart values file doesn't have reference to the variables which are required. I have to go in the [file](https://github.com/Azure/karpenter-provider-azure/blob/deb71b4a03885a5294912a39fbcac0e9956150d4/pkg/operator/options/options.go#L94-L114) to check required variables
- Also the options are to be passed via env as there is no reference for them in the [karpenter.settings](https://github.com/Azure/karpenter-provider-azure/blob/deb71b4a03885a5294912a39fbcac0e9956150d4/charts/karpenter/values.yaml#L151-L179)
- Why is there a need for SSH keys. 
- If karpenter is already asking for network contributor access why is there need to pass the vnet subnet ID.
- How to retrieve the bootstrap token ?

It should be made clear whether there is an actual usage of self-hosted installation or AKS is fully pedalling on NAP. If someone has the above issues resolved please let us know in this thread

**Comment by justinwalz** [comment]
To the maintainers: thank you for all your work on this project.
Quick ask... would a maintainer be able to chime in here? Is this issue something that is on the roadmap to be fixed, or should new users invest time in one of the workaround solutions?

As noted in the thread above there are problems with the current approach that give folks a good reason to hesitate on deploying this to production.

It seems like users can either
- Write a sidecar to poll and update a dedicated secret, and restart karpenter, as documented [in the above comment](https://github.com/Azure/karpenter-provider-azure/issues/695#issuecomment-3070185444)
- Do something similar, but with a CronJob (managed/deployed outside of the helm chart)
- Write a webhook, [as documented here in this blog](https://devcachein.wordpress.com/karpenter-token-refresh/)
- Some other creative solution?

I agree with the two above comments [[1]](https://github.com/Azure/karpenter-provider-azure/issues/695#issuecomment-2968345936),[[2]](https://github.com/Azure/karpenter-provider-azure/issues/695#issuecomment-3054204659). Karpenter could just watch the Secret directly and always have a fresh copy of the token, getting notified immediately if the contents changed. If bandwidth is low on the team, I could help add this contribution if it would get approval by maintainers.

This would solve problems for new users of Azure self managed karpenter, as well as help existing users simplify their configuration greatly. Thanks for reading!

**Comment by matthchr** [comment]
I will talk with other maintainers about this. I think what we need to do is add a controller watching the secret as you suggest @justinwalz. If you're interested in contributing one, that's awesome I would be happy to review that PR. Otherwise, I will take a crack at it but may not get to it til the new year as I have some vacation time coming up.

**Comment by justinwalz** [comment]
Thanks @matthchr! I'll let you know if I do.

However now that we have a workaround, I'll share it here in case others find this useful in the mean time.

Split the problem into two pieces:
- install time (tooling that usually runs once or infrequently)
- deploy time (tooling that runs continuously, gitops).

At install time, create a new Secret `karpenter-bootstrap-token` from the contents of the AKS managed secret (queried from `--field-selector type=bootstrap.kubernetes.io/token`).

Set this on the karpenter pods via snippet in the helm chart. 
```
    - name: KUBELET_BOOTSTRAP_TOKEN
      valueFrom:
        secretKeyRef:
          name: karpenter-bootstrap-token
          key: token
```


With GitOps, create a Deployment to keep the two secrets in sync and restart the karpenter deployment if a change was detected. This uses kubectl to watch both secrets, and call a function on change.
 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter-token-sync
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      serviceAccountName: karpenter-token-sync
      containers:
        - name: token-sync
          image: bitnami/kubectl
          command:
            - bash
            - "-c"
            - |
              set -euo pipefail

              LOCK_FILE="/tmp/karpenter-token-sync.lock"

              # Function to get and compare tokens
              check_and_sync_token() {
                # Acquire lock to prevent concurrent executions
                if ! mkdir "${LOCK_FILE}" 2>/dev/null; then
                  echo "Another sync operation is in progress, skipping..."
                  return 0
                fi

                # Ensure lock is released on exit
                trap 'rmdir "${LOCK_FILE}" 2>/dev/null || true' EXIT RETURN

                # Get the current bootstrap token from kube-system
                BOOTSTRAP_SECRETS_JSON=$(kubectl get secrets \
                  --field-selector type=bootstrap.kubernetes.io/token \
                  -n kube-system \
                  -o json 2>/dev/null || echo '{"items":[]}')

                SECRET_COUNT=$(echo "${BOOTSTRAP_SECRETS_JSON}" | jq -r '.items | length')

                if [ "${SECRET_COUNT}" -eq 0 ]; then
                  echo "WARNING: No bootstrap token secret found, will retry..."
                  return 1
                elif [ "${SECRET_COUNT}" -gt 1 ]; then
                  echo "ERROR: Multiple bootstrap token secrets found (${SECRET_COUNT})"
                  echo "Expected exactly one bootstrap token secret"
                  exit 1
                fi

                BOOTSTRAP_SECRET=$(echo "${BOOTSTRAP_SECRETS_JSON}" | jq -r '.items[0]')

                BOOTSTRAP_TOKEN_ID=$(echo "${BOOTSTRAP_SECRET}" | jq -r '.data["token-id"]' | base64 -d)
                BOOTSTRAP_TOKEN_SECRET=$(echo "${BOOTSTRAP_SECRET}" | jq -r '.data["token-secret"]' | base64 -d)

                # Combine into full token format
                BOOTSTRAP_TOKEN="${BOOTSTRAP_TOKEN_ID}.${BOOTSTRAP_TOKEN_SECRET}"

                # Get the karpenter-bootstrap-token secret (must exist)
                KARPENTER_SECRET=$(kubectl get secret karpenter-bootstrap-token \
                  -n kube-system \
                  -o json 2>/dev/null || echo '{}')

                if [ "${KARPENTER_SECRET}" = "{}" ]; then
                  echo "ERROR: karpenter-bootstrap-token secret does not exist"
                  echo "This secret must be created during initial Karpenter installation via Terraform platform workspace"
                  exit 1
                fi

                KARPENTER_TOKEN=$(echo "${KARPENTER_SECRET}" | jq -r '.data["token"] // empty' | base64 -d)

                # Compare the two tokens
                NEEDS_UPDATE=false
                if [ "${BOOTSTRAP_TOKEN}" != "${KARPENTER_TOKEN}" ]; then
                  echo "Token mismatch detected!"
                  echo "Bootstrap token: ${BOOTSTRAP_TOKEN_ID}.*****"
                  echo "Karpenter token: ${KARPENTER_TOKEN%%.*}.*****"
                  NEEDS_UPDATE=true
                fi

                # Update secret and restart karpenter if needed
                if [ "${NEEDS_UPDATE}" = "true" ]; then
                  echo "Updating karpenter-bootstrap-token secret..."

                  kubectl create secret generic karpenter-bootstrap-token \
                    -n kube-system \
                    --from-literal=token="${BOOTSTRAP_TOKEN}" \
                    --dry-run=client -o yaml | kubectl apply -f -

                  echo "Restarting karpenter deployment..."
                  kubectl rollout restart deployment/karpenter -n kube-system --timeout 180s

                  echo "Token sync completed at $(date)"
                else
                  echo "Tokens match, no update needed"
                fi
              }

              # Initial sync on startup
              echo "Performing initial token sync check on startup..."
              check_and_sync_token || true

              # Watch for changes to bootstrap token secrets (source of truth, auto-restart on failure)
              while true; do
                echo "Starting watch on source bootstrap token secrets..."
                kubectl get secrets \
                  --field-selector type=bootstrap.kubernetes.io/token \
                  -n kube-system \
                  --watch-only \
                  -o json | while read -r; do
                    echo "Source bootstrap token secret changed, checking sync..."
                    check_and_sync_token || true
                  done
                echo "Source bootstrap token watch exited, restarting in 5 seconds..."
                sleep 5
              done &

              # Watch for changes to karpenter-bootstrap-token secret (detect manual changes/drift, auto-restart on failure)
              while true; do
                echo "Starting watch on karpenter-bootstrap-token secret..."
                kubectl get secret karpenter-bootstrap-token \
                  -n kube-system \
                  --watch-only \
                  -o json | while read -r; do
                    echo "Karpenter bootstrap token secret changed, checking sync..."
                    check_and_sync_token || true
                  done
                echo "Karpenter bootstrap token watch exited, restarting in 5 seconds..."
                sleep 5
              done &

              # Also periodically check (as backup, every 5 minutes)
              while true; do
                sleep 300
                echo "Performing periodic token sync check (backup)..."
                check_and_sync_token || true
              done
```
