### ISSUE TITLE
Some zonal regions (like eastus2euap) are treated as non-zonal

### ISSUE THREAD

**Issue by tallaxes** [Azure/karpenter-provider-azure#731]
### Version

__Karpenter Version:__ v0.6.3 (NAP)

### Expected Behavior

`eastus2euap` (and likely some other regions) should be treated as zonal, supporting zone spread, etc.

### Actual Behavior

`eastus2euap` (and likely some other regions) is treated as non-zonal

This is very likely due to this region (and possibly other regions)  missing in the list of zonal regions:
https://github.com/Azure/karpenter-provider-azure/blob/e9b1ae6e4047f1b6675e2770c76d0617bf434c31/pkg/providers/instancetype/instancetypes.go#L375-L377

### Steps to Reproduce the Problem

Using zone topology spread in a workload in `eastus2euap` zone fails with "unsatisfiable topology constraint for topology spread"

### Resource Specs and Logs

Sample constraint snippet:

```yaml
          topologySpreadConstraints:
          - maxSkew: 1
            minDomains: 3
            topologyKey: "topology.kubernetes.io/zone"
            whenUnsatisfiable: DoNotSchedule
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
