### ISSUE TITLE
BYO CNI stopped working from v0.7.3

### ISSUE THREAD

**Issue by ppodevlabs** [Azure/karpenter-provider-azure#733]
### Version

Karpenter Version: v0.7.3+
Kubernetes Version:  v1.31.5

We have been running karpenter for a while without any issue and our karpenter parameter looks like this:
```
  env:
    - name: FEATURE_GATES
      value: Drift=true
    - name: LEADER_ELECT
      value: "false"
    - name: CLUSTER_NAME
      value: ${cluster_name}
    - name: CLUSTER_ENDPOINT
      value: ${cluster_endpoint}
    - name: NETWORK_PLUGIN
      value: "none"
    - name: NETWORK_PLUGIN_MODE
      value: ""
    - name: NETWORK_POLICY
      value: ""
    - name: VNET_GUID
      value: ${vnet_guid}
    - name: VNET_SUBNET_ID
      value: ${subnet_id}
    - name: NODE_IDENTITIES
      value: ${nodes_identity}
    # Azure client settings
    - name: ARM_SUBSCRIPTION_ID
      value: ${subscription_id}
    - name: LOCATION
      value: ${location}
    - name: KUBELET_IDENTITY_CLIENT_ID
      value: ""
    - name: AZURE_NODE_RESOURCE_GROUP
      value: ${nodes_resource_group_name}
```
Since a few days ago, due to issues with the node not joining the clusters( #723 ), we upgraded karpenter to v0.7.4 and fromthere  we have observed an issue causing the pods not being able to get an IP stating the error 

```
error: code = Unknown desc = failed to setup network for sandbox "bb7371978a28443f82b81d8ad78dd5883608fb1af54ba9b393705fffc7f01ab1": plugin type="azure-vnet" failed (add): IPAM Invoker Add failed with error: Failed to allocate pool: Failed to delegate: Failed to allocate address: No available addresses
```

We have tested and if we rollback to version 0.7.2 then it works without any issues. Looking at the code seems to be related to the changes introduced in https://github.com/Azure/karpenter-provider-azure/pull/697 and more precisely to this https://github.com/Azure/karpenter-provider-azure/pull/697/files#diff-25302a63d425cf7ccce03fb744105007fed5dd3672e408875d41d950ed5e6970R235

### Expected Behavior

Pods within karpenter nodes should be able to get an IP from the pod subnet

### Actual Behavior

Pods are not capable of getting an IP throwing the following an error from the `azure-vnet` plugin

### Steps to Reproduce the Problem

1. Create an aks cluster with you own CNI
2. Deploy karpenter in version =>0.7.3 with the configuration 
```
    - name: NETWORK_PLUGIN
      value: "none"
    - name: NETWORK_PLUGIN_MODE
      value: ""
    - name: NETWORK_POLICY
      value: ""
```

### Resource Specs and Logs

```
error: code = Unknown desc = failed to setup network for sandbox "bb7371978a28443f82b81d8ad78dd5883608fb1af54ba9b393705fffc7f01ab1": plugin type="azure-vnet" failed (add): IPAM Invoker Add failed with error: Failed to allocate pool: Failed to delegate: Failed to allocate address: No available addresses
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
