### ISSUE TITLE
SubnetIsFull, BYO Subnet, Self-Hosted

### ISSUE THREAD

**Issue by knechtionscoding** [Azure/karpenter-provider-azure#734]
### Version

__Karpenter Version:__ v0.7.1

__Kubernetes Version:__ v1.31.2

### Expected Behavior

Nodes are assigned an IP and join the cluster in the and pods can be scheduled on them

### Actual Behavior

When we try to opt in a pod to Karpenter management with proper tolerations, we get the following error:

RESPONSE 400: 400 Bad Request
ERROR CODE: SubnetIsFull
--------------------------------------------------------------------------------
SubnetIsFull: Subnet /subscriptions/<sub-id>/resourceGroups/<RG>/providers/Microsoft.Network/virtualNetworks/<VNetwork>/subnets/one with address prefix 10.0.0.0/20 does not have enough capacity for 1 IP addresses

We've confirmed that the subnet in question has plenty of IPs (somewhere around 1900). 

We run our regular node pools in this subnet so we know it has plenty of space, we've checked our other quotas to see if there's a problem, nothing there.

Is there some interaction with the subnet that happens from karpenter's side that isn't happening from a regular nodepool that I'm not aware of?

### Steps to Reproduce the Problem

Values.yaml:

```yaml
replicas: 1 # for better debugging experience
controller:
  env:
    - name: DISABLE_LEADER_ELECTION # disable leader election for better debugging / troubleshooting experience
      value: "true"
    # options
    - name: CLUSTER_NAME
      value: saas-germanywestcentral
    - name: CLUSTER_ENDPOINT
      value:<cluster endpoint>
    - name: KUBELET_BOOTSTRAP_TOKEN
      value: <token>
    - name: NETWORK_PLUGIN
      value: azure
    - name: NETWORK_PLUGIN_MODE
      value: ""
    - name: NETWORK_POLICY
      value: ""
    - name: VNET_SUBNET_ID
      value: <subnet ID>
    - name: NODE_IDENTITIES
      value: <node identity>
    # Azure client settings
    - name: ARM_SUBSCRIPTION_ID
      value: <Sub id>
    - name: LOCATION
      value: germanywestcentral
    - name: KUBELET_IDENTITY_CLIENT_ID
      value: ""
    - name: AZURE_NODE_RESOURCE_GROUP
      value: <Node RG>
    # managed karpenter settings
    - name: USE_SIG
      value: "false"
    - name: SIG_SUBSCRIPTION_ID
      value: ""
    - name: SSH_PUBLIC_KEY
      value: "<pubkey>"
serviceAccount:
  name: karpenter-sa
  annotations:
    azure.workload.identity/client-id: <client id>
podLabels:
  azure.workload.identity/use: "true"
logLevel: info
```

Networking Description of AKS Cluster:

```
Network configuration: Azure CNI Node Subnet
Pod CIDR: -
Service CIDR: <Custom CIDR>
DNS service IP: <Custom IP>
Network Policy: None
Load balancer: standard
Private cluster: Not enabled
Authorized IP ranges: Not enabled
Application Gateway ingress controller: Not enabled
```

### Resource Specs and Logs

Node claim is created, it sits pending and then:
--------------------------------------------------------------------------------
SubnetIsFull: Subnet /subscriptions/<sub-id>/resourceGroups/<RG>/providers/Microsoft.Network/virtualNetworks/<VNetwork>/subnets/one with address prefix 10.0.0.0/20 does not have enough capacity for 1 IP addresses

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
