### ISSUE TITLE
NAP disallows requirement label keys that are OK according to the public docs

### ISSUE THREAD

**Issue by amargherio** [Azure/karpenter-provider-azure#785]
### Version

__Karpenter Version:__ Uncertain - using the AKS managed add-on

__Kubernetes Version:__ v1.31.6

### Expected Behavior

When creating a NodePool object in a cluster with AKS NAP enabled, using labels such as `topology.kubernetes.io/zone` (or any other label in https://learn.microsoft.com/en-us/azure/aks/node-autoprovision?tabs=azure-cli#sku-selectors-with-well-known-labels) should be permitted.

### Actual Behavior

Using the `topology.kubernetes.io/zone` label as a requirement key, the following error is returned when attempting to create a NodePool object:

`The NodePool "apppool02" is invalid: spec.template.spec.requirements[0].key: Invalid value: "string": label domain "kubernetes.io" is restricted`

### Steps to Reproduce the Problem

1. Using AKS with Node Autoprovisioning enabled, apply the following NodePool YAML:
   ```yaml
   ---
   apiVersion: karpenter.sh/v1
   kind: NodePool
   metadata:
     name: ubuntu
   spec:
     disruption:
       consolidationPolicy: WhenEmptyOrUnderutilized
       consolidateAfter: 5m
     template:
       spec:
         nodeClassRef:
           group: karpenter.azure.com
           kind: AKSNodeClass
           name: default
         requirements:
           - key: topology.kubernetes.io/zone
             operator: In
             values:
               - eastus2
           - key: topology.kubernetes.io/region
             operator: In
             values:
               - eastus2
           - key: kubernetes.io/arch
             operator: In
             values:
               - amd64
           - key: kubernetes.io/os
             operator: In
             values:
               - linux
           - key: karpenter.sh/capacity-type
             operator: In
             values:
               - on-demand
           - key: karpenter.azure.com/sku-name
             operator: In
             values:
               - Standard_D2ds_v5
           - key: karpenter.azure.com/sku-storage-ephemeralos-maxsize
             operator: In
             values:
               - 100Gi
   ```

### Resource Specs and Logs

I don't have any Karpenter logs that I can share - the NodePool spec in the repro section is the only input required.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
