### ISSUE TITLE
Setting up NAP on existing cluster, get LinkedAuthorizationFailed in NodeClaims

### ISSUE THREAD

**Issue by hoopty** [Azure/karpenter-provider-azure#944]
### Version

__Kubernetes Version:__ v1.31.8

No helm release for `karpenter`, jus see these:
```
aks-managed-karpenter-overlay     	kube-system	15      	2025-06-08 00:05:36.989896191 +0000 UTC	deployed	karpenter-overlay-addon-0.1.0-67ffb6c0ffda7bf054bdff6fbbd34e5c83f1dc81     	           
aks-managed-karpenter-overlay-base	kube-system	15      	2025-06-08 00:04:56.480871344 +0000 UTC	deployed	karpenter-overlay-base-addon-0.1.0-9aa25dba81eee53fafe1b096c2d24821eda83616	   
```

### Expected Behavior

Expected nodes to get added

### Actual Behavior

NodeClaims have the following error: 

```
       PUT https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/MC_dev-eus-core-rg_dev-eus-core-aks-01_eastus/providers/Microsoft.Network/networkInterfaces/aks-gpulive-  4df7f
       --------------------------------------------------------------------------------
       RESPONSE 403: 403 Forbidden
       ERROR CODE: LinkedAuthorizationFailed
       --------------------------------------------------------------------------------
       {
         "error": {
           "code": "LinkedAuthorizationFailed",
           "message": "The client '9e0e4ddb-b441-4a34-a0e5-c0817d9e3cdf' with object id '9e0e4ddb-b441-4a34-a0e5-c0817d9e3cdf' has permission to perform action 'Microsoft.Network/networkInterfaces/write' on      scope '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/MC_xxx-xxx-core-rg_xxx-xxx-core-aks-01_eastus/providers/Microsoft.Network/networkInterfaces/aks-gpulive-4df7f'; however, it does not     have permission to perform action(s) 'Microsoft.Network/virtualNetworks/subnets/join/action' on the linked scope(s) '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxx-xxx-core-rg/providers/ Microsoft.Network/virtualNetworks/xxx-xxx-core-vnet-01/subnets/xxx-xxx-core-subnet-aks-01'...
```

### Steps to Reproduce the Problem

- Enabled NAP on existing AKS cluster
- Added NodePool for GPU nodes

### Resource Specs and Logs

NodePool:
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpulive
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
  template:
    metadata:
      labels:
        nvidia.com/device-plugin.config: default
        worlds.io/live: "true"
    spec:
      nodeClassRef:
        name: default
        kind: AKSNodeClass
        group: karpenter.azure.com
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
            # - spot
        - key: karpenter.azure.com/sku-name
          operator: In
          values:
            - Standard_NC4as_T4_v3
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
