### ISSUE TITLE
NAP CreateInstanceFailed on nodeclaims

### ISSUE THREAD

**Issue by hoopty** [Azure/karpenter-provider-azure#964]
### Version

```
aks-managed-karpenter-overlay     	kube-system	1421    	2025-06-13 05:36:18.076307149 +0000 UTC	deployed	karpenter-overlay-addon-0.1.0-67ffb6c0ffda7bf054bdff6fbbd34e5c83f1dc81     	           
aks-managed-karpenter-overlay-base	kube-system	1422    	2025-06-13 05:42:09.081121036 +0000 UTC	deployed	karpenter-overlay-base-addon-0.1.0-9aa25dba81eee53fafe1b096c2d24821eda83616	           
```
__Kubernetes Version:__ v1.31.8

### Expected Behavior

Nodes would provision.

### Actual Behavior

Seeing the following in my nodeclaims:
```  - lastTransitionTime: "2025-06-13T05:34:52Z"
    message: getting backend pools: failed to get next loadbalancer page: DefaultAzureCredential:
      failed to acquire a token.\nAttempted credentials:\n\tEnvironmentCredential:
      missing environment variable AZURE_TENANT_ID\n\tWorkloadIdentityCredential:
      no client ID specified. Check pod configuration or set ClientID in the options\n\tManagedIdentityCredential:
      failed to authenticate a system assigned identity. The endpoint responded with
      {\"error\":\"invalid_request\",\"error_description\":\"Multiple user assigned
      identities exist, please specify the clientId / resourceId of the identity in
      the token request\"}\n\tAzureCLICredential: fork/exec /bin/sh: no such file
      or directory\n\tAzureDeveloperCLICredential: fork/exec /bin/sh: no such file
      or directory
    observedGeneration: 1
    reason: CreateInstanceFailed
    status: Unknown
    type: Launched
```

### Steps to Reproduce the Problem

Enabled NAP for an existing AKS cluster, it was working but started seeing this issue.

Seeing this on multiple node pools.

### Resource Specs and Logs

node pool definition:
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu-batch
spec:
  weight: 10
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 1m
  template:
    metadata:
      labels:
        worlds.io/batch: "true"
    spec:
      nodeClassRef:
        group: karpenter.azure.com
        kind: AKSNodeClass
        name: default
      taints:
        - key: nvidia.com/gpu
          value: "true"
          effect: NoSchedule
      requirements:
        - key: karpenter.azure.com/sku-name
          operator: In
          values:
            - Standard_NC4as_T4_v3
            - Standard_NC8as_T4_v3
        # - key: karpenter.azure.com/sku-family
        #   operator: In
        #   values:
        #     - N
        # - key: karpenter.azure.com/sku-gpu-name
        #   operator: In
        #   values:
        #     - t4
        # - key: karpenter.azure.com/sku-version
        #   operator: In
        #   values:
        #     - "3"
        # - key: karpenter.azure.com/sku-storage-premium-capable
        #   operator: In
        #   values:
        #     - "true"
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
      startupTaints:
        - effect: NoExecute
          key: node.cilium.io/agent-not-ready
          value: "true"
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
